raf/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from tag.views import TagList,TagCreate,TagDelete,TagUpdate,TagDetail
from django.views.generic import TemplateView,RedirectView
from user import urls as user_urls


urlpatterns = [
    url(r'^$',
        RedirectView.as_view(pattern_name ='tag_list_view',
        permanent = False)),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/$',TemplateView.as_view(template_name='blog/post_list.html'),name='post_list'),
    url(r'^tag/$',TagList.as_view(),name = 'tag_list_view'),
    url(r'^tag/create/$',TagCreate.as_view(),name='tag_create'),
    url(r'^tag/(?P<slug>[\w-]+)/delete/$',TagDelete.as_view(),name='tag_delete'),
    url(r'^tag/(?P<slug>[\w-]+)/detail/$',TagDetail.as_view(),name='tag_detail'),
    url(r'^tag/(?P<slug>[\w-]+)/update/$',TagUpdate.as_view(),name='tag_update'),

    url(r'^user/',include(user_urls,app_name='user',namespace='dj-auth')),



]

user/urls.py
from django.conf.urls import include, url
from django.contrib.auth import \
    views as auth_views
from django.contrib.auth.forms import \
    AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    RedirectView, TemplateView)

from .views import (
    ActivateAccount, CreateAccount,
    DisableAccount, ResendActivationEmail,ProfileDetail,ProfileUpdate,PublicProfileDetail)

password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:pw_reset_start',
            permanent=False)),
    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'user/password_change_form.html',
         'post_change_redirect': reverse_lazy(
            'dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
            'user/password_reset_form.html',
         'email_template_name':
            'user/password_reset_email.txt',
         'subject_template_name':
            'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'user/password_reset_complete.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='pw_reset_complete'),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=(
                'dj-auth:resend_activation'),
            permanent=False)),
    url(r'^create/$',
        CreateAccount.as_view(),
        name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(
            template_name=(
                'user/user_create_done.html')),
        name='create_done'),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name='disable'),
    url(r'^login/$',
        auth_views.login,
        {'template_name': 'user/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'template_name': 'user/logged_out.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='logout'),
    url(r'^password/',
        include(password_urls)),
    url(r'^profile/$',
        ProfileDetail.as_view(),
        name='profile'),

    url(r'profile/edit$',
        ProfileUpdate.as_view(),
        name='profile_update'),

    url(r'(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name='public_profile'),

]

user/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.contrib.auth.models import AbstractBaseUser,PermissionsMixin,BaseUserManager
from datetime import date



# Create your models here.





class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=30,unique=True)
    about = models.TextField()
    joined = models.DateTimeField('Date joined',auto_now_add=True)


    def __str__(self):
        return self.user.get_username()


    def get_absolute_url(self):
        return reverse('dj-auth:public_profile',kwargs={'slug':self.slug})
    def get_update_url(self):
        return reverse('dj-auth:profile_update')


class UserManager(BaseUserManager):

    def _create_user(self,email,password, **kwargs):
        email = self.normalize_email(email)
        is_staff = kwargs.pop('is_staff',False)
        is_superuser = kwargs.pop('is_superuser',False)
        user = self.model(email=email,is_staff=is_staff,is_superuser=is_superuser,**kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self,email,password=None,**extra_fields):
        return self._create_user(email,password,**extra_fields)


    def create_superuser(self,email,password,**extra_fields):
        return self._create_user(email,password,is_superuser=True,is_staff=True,**extra_fields)



class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(
        'email address',
        max_length=254,
        unique=True)
    is_staff = models.BooleanField(
        'staff status',
        default=False,
        help_text=(
            'Designates whether the user can '
            'log into this admin site.'))
    is_active = models.BooleanField(
        'active',
        default=True,
        help_text=(
            'Designates whether this user should '
            'be treated as active. Unselect this '
            'instead of deleting accounts.'))

    USERNAME_FIELD = 'email'
    objects = UserManager()

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return self.profile.get_absolute_url()

    def get_full_name(self):
        return self.profile.name

    def get_short_name(self):
        return self.profile.name

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from django.contrib.auth import get_user_model
from .utils import ActivationMailFormMixin
from django.core.exceptions import ValidationError
import logging
from .models import Profile
from django.utils.text import slugify


logger = logging.getLogger(__name__)




class ResendActivationEmailForm(ActivationMailFormMixin,forms.Form):
    email = forms.EmailField()

    mail_validation_error = ('Could not re send activation email please try again later (sorry)')

    def save(self,**kwargs):
        User = get_user_model()
        try:
            user = User.objects.get(email=self.cleaned_data['email'])
        except:
            logger.warning ('Resend Activation Email: no user with email: {}'.format(self.cleaned_data['email']))
            return None
        self.send_mail(user=user,**kwargs)
        return user





class UserCreationForm(ActivationMailFormMixin,BaseUserCreationForm):
    name = forms.CharField(max_length=255)
    mail_validation_error = (
        'User created could not sent activation email Please try again later (Sorry!!)'
    )
    class Meta:
        model = get_user_model()
        fields = ['name','email']


    def clean_username(self):
        name = self.cleaned_data['name']
        disallowed = (
            'activate',
            'create',
            'disabel',
            'login',
            'logout',
            'password',
            'profile',
        )
        if name is disallowed:
            raise ValidationError ("A user with that username already exist")
        return name



    def save(self, **kwargs):
        user = super().save(commit=False)
        if not user.pk:
            user.is_active = False
            send_mail = True

        else :
            send_mail = False

        user.save()
        self.save_m2m()
        Profile.objects.update_or_create(user = user,defaults={'name':self.cleaned_data['name'],
                                                               'slug':slugify(self.cleaned_data['name'])})

        if send_mail:
            self.send_mail(user= user, **kwargs)
        return user

user/views.py
from django.shortcuts import render
from django.contrib.auth import get_user, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from django.template.response import TemplateResponse
from raf.settings import dev

################## Signup ####################
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect, render
from django.core.urlresolvers import reverse_lazy
from .forms import UserCreationForm
from .utils import MailContextViewMixin,ProfilGetObjectMixin
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.messages import error
from django.contrib.auth import get_user_model
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.contrib.messages import success
from django.views.decorators.cache import never_cache
from .forms import ResendActivationEmailForm
from .models import Profile
from django.views.generic import DeleteView,View,DetailView,UpdateView


class DisableAccount(View):
    success_url = dev.LOGIN_REDIRECT_URL
    template_name = 'user/user_confirm_delete.html'

    @method_decorator(login_required)
    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(request, self.template_name)

    @method_decorator(login_required)
    @method_decorator(csrf_protect)
    def post(self, request):
        user = get_user(request)
        user.set_unusable_password()
        user.is_active = False
        user.save()
        logout(request)
        return redirect(self.success_url)


class Signup(View):
    form_class = UserCreationForm
    success_url = reverse_lazy('tag_list_view')
    template_name = 'user/signup.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})

    def post(self, request):
        bound_form = UserCreationForm(request.POST)
        if bound_form.is_valid():
            bound_form.save()
            username = bound_form.cleaned_data.get('username')
            raw_password = bound_form.cleaned_data.get('password1')
            email = bound_form.cleaned_data.get('email')
            user = authenticate(username=username, password=raw_password, email=email)
            login(request, user)
            return redirect(self.success_url)



        return render(request, self.template_name, {'form': bound_form})


class CreateAccount(MailContextViewMixin, View):
    form_class = UserCreationForm
    success_url = reverse_lazy('dj-auth:create_done')
    template_name = 'user/user_create.html'

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(request, self.template_name, {'form': self.form_class()})

    @method_decorator(csrf_protect)
    @method_decorator(sensitive_post_parameters('password1', 'password2'))
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            bound_form.save(**self.get_save_kwargs(request))
            if bound_form.mail_sent:
                return redirect(self.success_url)
            else :
                errs = bound_form.non_field_errors()
                for err in errs:
                    error(request,err)

        return TemplateResponse(request,self.template_name,{'form':bound_form})



class ActivateAccount(View):
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'user/user_activate.html'



    def get(self,request,uidb64,token):
        User = get_user_model()
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError,ValueError,OverflowError,User.DoesNotExist):
            user = None

        if (user is not  None and token_generator.check_token(user,token)):
            user.is_active = True
            user.save()
            success(request,'user activated You may now login')
            return redirect(self.success_url)
        else:
            return TemplateResponse(request,self.template_name)

class ResendActivationEmail(
        MailContextViewMixin, View):
    form_class = ResendActivationEmailForm
    success_url = reverse_lazy('dj-auth:login')
    template_name = 'user/resend_activation.html'

    @method_decorator(csrf_protect)
    def get(self, request):
        return TemplateResponse(
            request,
            self.template_name,
            {'form': self.form_class()})

    @method_decorator(csrf_protect)
    def post(self, request):
        bound_form = self.form_class(request.POST)
        if bound_form.is_valid():
            user = bound_form.save(
                **self.get_save_kwargs(request))
            if (user is not None
                    and not bound_form.mail_sent):
                errs = (
                    bound_form.non_field_errors())
                for err in errs:
                    error(request, err)
                if errs:
                    bound_form.errors.pop(
                        '__all__')
                return TemplateResponse(
                    request,
                    self.template_name,
                    {'form': bound_form})
        success(
            request,
            'Activation Email Sent!')
        return redirect(self.success_url)



class ProfileDetail(ProfilGetObjectMixin,DetailView):
    model = Profile


class ProfileUpdate(ProfilGetObjectMixin,UpdateView):
    model = Profile
    fields = ('about',)
    template_name_suffix = '_form_update'


class PublicProfileDetail(DetailView):
    model = Profile

user/templates/user/logged_out.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Tag Create</h2>
{% endblock %}


{% block content %}

 <p> You have successfully loged out</p>

  {% include 'user/logon_form.html' with login_button='Log Back In' %}


{% endblock %}

user/templates/user/login.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Tag Create</h2>
{% endblock %}


{% block content %}



{% if messages %}
  <div class="alert alert-success" role="alert">
    {% for message in messages %}
      <button type="button" class="close" data-dismiss="alert" {% if message.tags %} class="{{ message.tags }}"{% endif %}>&times;</button>{{ message }}
    {% endfor %}
  </div>

{% endif %}

 {% include 'user/logon_form.html' %}


{% endblock %}


 {% block button %}
   <li><a href="{% url 'dj-auth:create' %}">Register New Account</a></li>
   <li><a href="{% url 'dj-auth:pw_reset_start' %}"> Forgotten password?</a></li>


 {% endblock %}

user/templates/user/password_change_done.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Password Change</h2>
{% endblock %}


{% block content %}

 <p> Password Successfully changed !!</p>



{% endblock %}

user/templates/user/password_change_form.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Password Change</h2>
{% endblock %}


{% block content %}

<form action="{% url 'dj-auth:pw_change' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit">Change Password</button>
  </form>


{% endblock %}

user/templates/user/password_reset_confirm.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Password Reset Confirm</h2>
{% endblock %}


{% block content %}

 {% if validlink %}
        <p>Enter a new password below.</p>
        <form action="{{ request.path }}" method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button class="button-primary" type="submit">Save New Password</button>
        </form>
      {% else %}
        <p>This reset link is no longer valid.</p>
        <p>Please request a new reset email
          <a href="{% url 'dj-auth:pw_reset_start' %}">here</a>.</p>
      {% endif %}

{% endblock %}

user/templates/user/password_reset_form.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Password reset</h2>
{% endblock %}


{% block content %}

<form action="{% url 'dj-auth:pw_reset_start' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
    <button type="submit">Send me reset Instructions</button>
  </form>


{% endblock %}

user/templates/user/password_reset_sent.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Password Reset Sent</h2>
{% endblock %}


{% block content %}

 <p>Password reset email sent!</p>
 <p>Please check your inbox and spam box.</p>

{% endblock %}

user/templates/user/profile_detail.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>{{profile.user.get_full_name|title}}'s Profile</h2>
{% endblock %}


{% block content %}
 <h2>About {{profile.user.get_full_name}}</h2>
 {{profile.about|default:"No Profile"|linebreaks}}

{% endblock %}


 {% block button %}
 {% if user.pk == profile.user.pk %}
  <ul>
       <li><a href="{% url 'dj-auth:profile_update' %}">Profile update</a></li>
      <li ><a href="{% url 'dj-auth:pw_change' %}">Change Password</a></li>
      <li><a href="{% url 'dj-auth:disable' %}">Disable Account</a></li>
  </ul>
 {% endif %}


 {% endblock %}

user/templates/user/resend_activation.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Resend Actvation mail</h2>
{% endblock %}


{% block content %}

 <form
 action="{% url 'dj-auth:resend_activation' %}"
  method="post">
  {% csrf_token %}
  {{ form.as_p }}
     <button type="submit">Resend Activation Email</button>
  </form>


{% endblock %}


 {% block button %}



 {% endblock %}

user/templates/user/signup.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Tag Create</h2>
{% endblock %}


{% block content %}

 <form
 action="{% url 'dj-auth:signup' %}"
  method="post">
  {% csrf_token %}
  {{ form.as_p }}
     <button type="submit">Signup</button>
  </form>


{% endblock %}


 {% block button %}



 {% endblock %}

user/templates/user/user_active.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

user/templates/user/user_confirm_delete.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>User Delete</h2>
{% endblock %}


{% block content %}

  <p>Disable your account?</p>
  <p>This cannot be undone.</p>
  <form action="{% url 'dj-auth:disable' %}" method="post">
     {% csrf_token %}
     <button type="submit">Disable Account</button>
  </form>


{% endblock %}


 {% block button %}



 {% endblock %}

user/templates/user/user_create.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>User Create</h2>
{% endblock %}


{% block content %}

 <form
 action="{% url 'dj-auth:create' %}"
  method="post">
  {% csrf_token %}
  {{ form.as_p }}
     <button type="submit">Create New Account</button>
  </form>


{% endblock %}


 {% block button %}



 {% endblock %}

user/templates/user/user_create_done.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>User Create done!!!</h2>
{% endblock %}


{% block content %}

  <p>Your account has been created!</p>
  <p>Please check your email for the activation link.</p>


{% endblock %}


 {% block button %}



 {% endblock %}