raf/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from tag.views import TagList,TagCreate,TagDelete,TagUpdate,TagDetail
from django.views.generic import TemplateView,RedirectView
from user import urls as user_urls


urlpatterns = [
    url(r'^$',
        RedirectView.as_view(pattern_name ='tag_list_view',
        permanent = False)),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/$',TemplateView.as_view(template_name='blog/post_list.html'),name='post_list'),
    url(r'^tag/$',TagList.as_view(),name = 'tag_list_view'),
    url(r'^tag/create/$',TagCreate.as_view(),name='tag_create'),
    url(r'^tag/(?P<slug>[\w-]+)/delete/$',TagDelete.as_view(),name='tag_delete'),
    url(r'^tag/(?P<slug>[\w-]+)/detail/$',TagDetail.as_view(),name='tag_detail'),
    url(r'^tag/(?P<slug>[\w-]+)/update/$',TagUpdate.as_view(),name='tag_update'),

    url(r'^user/',include(user_urls,app_name='user',namespace='dj-auth')),



]

user/urls.py
from django.conf.urls import include, url
from django.contrib.auth import \
    views as auth_views
from django.contrib.auth.forms import \
    AuthenticationForm
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    RedirectView, TemplateView)

from .views import (
    ActivateAccount, CreateAccount,
    DisableAccount, ResendActivationEmail,ProfileDetail,ProfileUpdate,PublicProfileDetail)

password_urls = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:pw_reset_start',
            permanent=False)),
    url(r'^change/$',
        auth_views.password_change,
        {'template_name':
            'user/password_change_form.html',
         'post_change_redirect': reverse_lazy(
            'dj-auth:pw_change_done')},
        name='pw_change'),
    url(r'^change/done/$',
        auth_views.password_change_done,
        {'template_name':
            'user/password_change_done.html'},
        name='pw_change_done'),
    url(r'^reset/$',
        auth_views.password_reset,
        {'template_name':
            'user/password_reset_form.html',
         'email_template_name':
            'user/password_reset_email.txt',
         'subject_template_name':
            'user/password_reset_subject.txt',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_sent')},
        name='pw_reset_start'),
    url(r'^reset/sent/$',
        auth_views.password_reset_done,
        {'template_name':
            'user/password_reset_sent.html'},
        name='pw_reset_sent'),
    url(r'^reset/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'template_name':
            'user/password_reset_confirm.html',
         'post_reset_redirect': reverse_lazy(
            'dj-auth:pw_reset_complete')},
        name='pw_reset_confirm'),
    url(r'reset/done/$',
        auth_views.password_reset_complete,
        {'template_name':
            'user/password_reset_complete.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='pw_reset_complete'),
]

urlpatterns = [
    url(r'^$',
        RedirectView.as_view(
            pattern_name='dj-auth:login',
            permanent=False)),
    url(r'^activate/'
        r'(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}'
        r'-[0-9A-Za-z]{1,20})/$',
        ActivateAccount.as_view(),
        name='activate'),
    url(r'^activate/resend/$',
        ResendActivationEmail.as_view(),
        name='resend_activation'),
    url(r'^activate',
        RedirectView.as_view(
            pattern_name=(
                'dj-auth:resend_activation'),
            permanent=False)),
    url(r'^create/$',
        CreateAccount.as_view(),
        name='create'),
    url(r'^create/done/$',
        TemplateView.as_view(
            template_name=(
                'user/user_create_done.html')),
        name='create_done'),
    url(r'^disable/$',
        DisableAccount.as_view(),
        name='disable'),
    url(r'^login/$',
        auth_views.login,
        {'template_name': 'user/login.html'},
        name='login'),
    url(r'^logout/$',
        auth_views.logout,
        {'template_name': 'user/logged_out.html',
         'extra_context':
             {'form': AuthenticationForm}},
        name='logout'),
    url(r'^password/',
        include(password_urls)),
    url(r'^profile/$',
        ProfileDetail.as_view(),
        name='profile'),

    url(r'profile/edit$',
        ProfileUpdate.as_view(),
        name='profile_update'),

    url(r'(?P<slug>[\w\-]+)/$',
        PublicProfileDetail.as_view(),
        name='public_profile'),

]

tag/models.py
from django.db import models
from django.core.urlresolvers import reverse


# Create your models here.


class Tag(models.Model):
    tag_name = models.CharField(max_length=50,unique=True)
    slug = models.SlugField(max_length=50, unique=True,help_text='a label for url')

    def __str__(self):
        return self.tag_name

    def get_absolute_url(self):
        return reverse('tag_detail',kwargs={'slug':self.slug})

    def get_delete_url(self):
        return reverse('tag_delete',kwargs={'slug':self.slug})

    def get_update_url(self):
        return reverse('tag_update',kwargs={'slug':self.slug})

tag/forms.py
from django import  forms
from .models import Tag
from django.core.exceptions import ValidationError

class SlugCleanMixin:
    def clean_slug(self):
        new_slug = (self.cleaned_data['slug'].lower())
        if new_slug=='create':
            raise ValidationError('Slug may not be create ')
        return new_slug



class TagForm(forms.ModelForm):
    class Meta:
        model  = Tag
        fields = '__all__'

    def clean_tag_name(self):
        return (self.cleaned_data['tag_name'].lower())

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()

tag/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse,reverse_lazy
from django.views.generic import ListView, View, CreateView,DeleteView,UpdateView,DetailView
from tag.models import Tag
from tag.forms import TagForm
from django.contrib.messages.views import SuccessMessageMixin
from .utils import PageMixin
################################### Permission #######################
from django.contrib.auth.decorators import login_required,permission_required
from django.utils.decorators import method_decorator
from .decorators import (require_authenticated_permission, class_login_required,)


# Create your views here.


class TagList(ListView):
    paginate_by = 2
    model = Tag

@require_authenticated_permission('tag.add_tag')
class TagCreate(SuccessMessageMixin, CreateView):
    form_class = TagForm
    model = Tag

    success_url = reverse_lazy('tag_list_view')
    success_message = 'Another tag is created!!!!'





#@require_authenticated_permission('tag.view_tag')
class TagDetail(DetailView):
    model = Tag

@require_authenticated_permission('tag.delete_tag')
class TagDelete(DeleteView):
    model = Tag
    success_url = reverse_lazy('tag_list_view')

@require_authenticated_permission('tag.change_tag')
class TagUpdate(SuccessMessageMixin,UpdateView):
    model = Tag
    fields = '__all__'
    template_name_suffix = '_form_update'
    success_url = reverse_lazy('tag_list_view')
    success_message = 'Successfully Updated!!!!'

tag/templates/tag/base_tag.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

    <title>Blog</title>


    <link rel="stylesheet" type="text/css" href="{% static 'post.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'signin.css' %}">
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="nav">
          <a class="nav-link active" href="{% url 'post_list' %}">Home</a>
          <a class="nav-link" href="#">Department</a>
          <a class="nav-link" href="{% url 'tag_list_view' %}">Tags</a>
          <a class="nav-link" href="#">About</a>
          <a class="nav-link" href="#">Contact</a>
          {% if user.is_authenticated %}
              <a class="nav-link" href="{% url 'dj-auth:logout'%}?next={{request.path}}">Logout</a>
              <a class="nav-link" href="{% url 'dj-auth:profile'%}">profile</a>
          {% else %}
              <a class="nav-link" href="{% url 'dj-auth:login'%}?next={{request.path}}">Login</a>
              <a class="nav-link" href="{% url 'dj-auth:create'%}">Register</a>
          {% endif %}
        </nav>
      </div>
    </div>

    <div class="blog-header">
      <div class="container">
        <div class='bog-title'>
           {% block title %}
           {% endblock %}
        </div>
         
      </div>
    </div>

    <div class="container">

      <div class="row">

        <div class="col-sm-8 blog-main">
          {% block content %}
          {% endblock %}

           
        </div><!-- /.blog-main -->

           <div class="col-sm-3 offset-sm-1 blog-sidebar">
              {% block button %}
              {% endblock %}

        </div><!-- /.blog-sidebar -->

         

      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>Blog template built for <a href="https://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>


    <!-- Bootstrap core JavaScript
    ================================================== -->
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

  </body>
</html>

tag/templates/tag/tag_confirm_delete.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Tag Update</h2>
{% endblock %}


{% block content %}

  <form action="{{ tag.get_delete_url }}" method="post">
        {% csrf_token %}
        <p>
          Are you sure you want to delete
          tag {{ tag.name }}?
        </p>
        <a href="{{ tag.get_absolute_url }}" class="button button-primary">Cancel</a>
        <button type="submit">Delete Tag</button>
  </form>


{% endblock %}

tag/templates/tag/tag_detail.html
{% extends parent_template|default:"tag/base_tag.html" %}

{% block title %}
<h2>{{ tag.tag_name|title }}</h2>
{% endblock %}

tag/templates/tag/tag_form.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Tag Create</h2>
{% endblock %}


{% block content %}

  <form action="{% url 'tag_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-primary" type="submit">Create Tag</button>
  </form>


{% endblock %}

tag/templates/tag/tag_form_update.html
 {% extends parent_template|default:"tag/base_tag.html" %}




{% block title %}
<h2>Tag Update</h2>
{% endblock %}


{% block content %}

  <form action="{{ tag.tag_update_url }}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="button-primary" type="submit">Update Tag</button>
      </form>


{% endblock %}

tag/templates/tag/tag_list.html
{% extends parent_template|default:"tag/base_tag.html" %}

{% block title %}
<h2>Tag List</h2>
{% endblock %}


{% block content %}






{% if messages %}
  <div class="alert alert-success" role="alert">
    {% for message in messages %}
      <button type="button" class="close" data-dismiss="alert" {% if message.tags %} class="{{ message.tags }}"{% endif %}>&times;</button>{{ message }}
    {% endfor %}
  </div>

{% endif %}

    <ul>
    {% for tag in tag_list %}
    <li><a href="{{tag.get_absolute_url}}">{{tag.tag_name|title}}</a></li>
      {% if perms.tag.change_tag %}
     <a href="{{ tag.get_update_url }}" class="button">Edit</a>
        {% endif %}
        {% if perms.tag.delete_tag %}
     <a href="{{ tag.get_delete_url }}" class="button">Delete</a>
        {% endif %}
    {% empty %}
     <li><em>There are currently no Tags available.</em></li>
    </ul>
    {% endfor %}



     {% if is_paginated %}

    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endif %}


{% endblock %}


{% block button %}
    {% if perms.tag.add_tag %}
    <a href="{% url 'tag_create' %}" class="button button-primary">Create New Tag</a>
     {% endif %}
{% endblock %}